stages:
    - Build

compile_pdf:
    stage: Build
    image: aergus/latex
    before_script:
        - apt-get install -y xindy
    script:
        - make
    artifacts:
        paths:
            - main.pdf
